---
- hosts: localhost
  remote_user: root
  gather_facts: False
  vars_files:
    - aws_instances/vars/main.yml
  roles:
    - aws_instances

- hosts: master
  gather_facts: False
  remote_user: ec2-user
  become: yes
  become_user: root
  become_method: sudo
  vars_files:
    - kubernetes_role/vars/main.yml
  vars:
    - ansible_ssh_private_key_file: /root/prithvi.pem
  roles: 
    - kubernetes_role

- hosts: workers
  gather_facts: False
  remote_user: ec2-user
  become: yes
  become_user: root
  become_method: sudo
  vars:
    - ansible_ssh_private_key_file: /root/prithvi.pem
    - token_cmd: "{{ hostvars[groups['master'][0]]['token'] }}"
  roles:
    - worker_node
  

- hosts: master
  gather_facts: False
  remote_user: ec2-user
  vars: 
    - ansible_ssh_private_key_file: /root/prithvi.pem
  roles:
    - overlay
